import type {Adventure,CalendarEvent,Idea} from './types';
export const ideas:Idea[]=[
{id:'olive',title:'Olive Garden Vaughan',description:'Italian dinner date night',category:'Food',status:'Confirmed',tags:['Dinner'],addedBy:'Liz',createdAt:'2026-07-08',optionalLocation:'Vaughan'},
{id:'gallery',title:'McMichael Gallery',description:'Art, nature, inspiration',category:'Culture',status:'Tentative',tags:['Art'],addedBy:'Jordan',createdAt:'2026-07-07',optionalLocation:'Kleinburg'},
{id:'ford',title:'Ford concert',description:'Live music under the stars',category:'Concerts',status:'Confirmed',tags:['Music'],addedBy:'Liz',createdAt:'2026-07-06'},
{id:'camp',title:'Camping trip',description:'Algonquin Park getaway',category:'Camping & Travel',status:'Idea',tags:['Weekend'],addedBy:'Jordan',createdAt:'2026-07-05'},
{id:'ikea',title:'IKEA organizing bin',description:'Storage glow-up',category:'Errands',status:'Idea',tags:['Home'],addedBy:'Liz',createdAt:'2026-07-04',optionalLocation:'Vaughan'}];
export const adventures:Adventure[]=[{id:'vaughan',title:'Vaughan Day',description:'A full day of little errands, inspiring art, and a cozy dinner together.',date:'2026-07-18',startTime:'11:00 AM',endTime:'6:30 PM',status:'Confirmed',coverImage:'/vaughan-day.png',location:'Vaughan, Ontario',addedBy:'Jordan',updatedBy:'Liz',completed:false,favorite:true,notes:'Bring the return receipt. Leave a little extra time to walk the gallery grounds.',links:[{id:'l1',label:'McMichael Collection',url:'https://mcmichael.com'},{id:'l2',label:'Olive Garden Vaughan',url:'https://www.olivegarden.com'}],checklist:[{id:'c1',label:'Pack gym equipment return',completed:true},{id:'c2',label:'Bring IKEA measurements',completed:false},{id:'c3',label:'Gallery tickets',completed:false}],stops:[{id:'s1',title:'Return gym equipment',location:'Home',startTime:'11:00 AM',sortOrder:1,optionalTravelTime:'25 min'},{id:'s2',title:'IKEA Vaughan',location:'Shop & organize',startTime:'11:45 AM',endTime:'1:15 PM',sortOrder:2,optionalTravelTime:'40 min'},{id:'s3',title:'McMichael Canadian Art Collection',location:'Art & nature',startTime:'1:45 PM',endTime:'3:45 PM',sortOrder:3,optionalTravelTime:'15 min'},{id:'s4',title:'Olive Garden Vaughan',location:'Dinner',startTime:'4:15 PM',endTime:'6:00 PM',sortOrder:4,optionalTravelTime:'10 min'},{id:'s5',title:'Head home',location:'Wind down',startTime:'6:30 PM',sortOrder:5,optionalTravelTime:'30 min'}]},{id:'islands',title:'Toronto Islands Picnic',description:'Bikes, snacks, and sunset by the water.',date:'2026-06-20',startTime:'2:00 PM',endTime:'9:00 PM',status:'Confirmed',location:'Toronto Islands',addedBy:'Liz',updatedBy:'Jordan',completed:true,favorite:false,notes:'Our best sunset yet.',links:[],checklist:[],stops:[]}];
export const calendarEvents:CalendarEvent[]=[{id:'e1',title:'Camping Trip',subtitle:'Algonquin Park',date:'2026-07-14',category:'Camping & Travel',status:'Confirmed',allDay:true},{id:'e2',title:'Coffee & Plan',subtitle:'Home',date:'2026-07-18',startTime:'10:00 AM',endTime:'11:00 AM',category:'Dates',status:'Confirmed'},{id:'e3',title:'Vaughan Day',subtitle:'Itinerary',date:'2026-07-18',startTime:'12:00 PM',endTime:'1:00 PM',category:'Dates',status:'Confirmed',adventureId:'vaughan'},{id:'e4',title:'Dinner',subtitle:'Olive Garden Vaughan',date:'2026-07-18',startTime:'6:00 PM',endTime:'7:00 PM',category:'Food',status:'Confirmed'},{id:'e5',title:'Ford concert',subtitle:'Budweiser Stage',date:'2026-07-30',startTime:'8:00 PM',endTime:'10:30 PM',category:'Concerts',status:'Confirmed'}];
